name: 'simple-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          ayx-server-api-url: 'http://ec2-3-66-136-169.eu-central-1.compute.amazonaws.com/webapi/'
          ayx-server-client-id: '8DA78CE09C0E5D1abf4927846637f9a02e196b8eff52b61f03246ad16ad2c81125ef4a80920db80'
          ayx-server-client-secret: '1f675a0f8d2c572ddd02005a3396fe7e89706fe4a39e0d5f39cf9b6463aecec8'
          collection-to-test: '00_Data_Ingestion'
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
            path: |
              *.tgz
              results.json
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()    
        with:
          name: Test Results            
          path: results.json            
          reporter: mocha-json
